// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Notfound: typeof import('./src/components/icons/Notfound.vue')['default']
    QuerySettings: typeof import('./src/components/QuerySettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlResult: typeof import('./src/components/SqlResult.vue')['default']
    UploadDataset: typeof import('./src/components/UploadDataset.vue')['default']
    Welcome: typeof import('./src/components/icons/Welcome.vue')['default']
  }
}

export {}
